### ISSUE TITLE
Change access level for devices field

### ISSUE THREAD

**Issue by fatadel** [WebThingsIO/gateway-addon-node#101]
In the Adapter class, the field `devices` is declared as private. However, in the `ThingURLAdapter` the field is accessed directly - https://github.com/WebThingsIO/thing-url-adapter/blob/23b0f08ebc17b9df54c084b5191fa6883f90da01/thing-url-adapter.js#L618.  And it's possible only because js simply doesn't care, but we cannot do the same if creating an adapter in ts. So, I would like to propose to change this field to protected or public instead.

The issue appeared while working on [the new adapter](https://github.com/WebThingsIO/wot-adapter).

@tim-hellhake 
@benfrancis
@relu91

**Comment by tim-hellhake** [comment]
There is a [getter](https://github.com/WebThingsIO/gateway-addon-node/blob/v1.0.0/src/adapter.ts#L93) for the `devices` field.

**Comment by fatadel** [comment]
@tim-hellhake, thank you very much, I've missed that.
