### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by tim-hellhake** [WebThingsIO/gateway-addon-node#41]
May I migrate this project to typescript?

This would also benefit JS developers as VS Code supports code completion from typings.

**Comment by mrstegeman** [comment]
If you have the time, feel free!

**Comment by tim-hellhake** [comment]
Thanks :)

**Comment by GiviMAD** [comment]
If nobody is working on it, can I take this task?

**Comment by benfrancis** [comment]
@GiviMAD I don't think anyone is working on this, and contributions are welcome!

Question: Is this intended to be in addition to the current vanilla JavaScript version or to replace it? I would personally like to keep a vanilla JavaScript option available.

**Comment by tim-hellhake** [comment]
@GiviMAD I already converted approximately 90 percent of the JS code. I’ll do the rest in the next days.

**Comment by benfrancis** [comment]
Oh, sorry @tim-hellhake I didn't know you were working on this :)

**Comment by tim-hellhake** [comment]
@benfrancis Nevermind :)
Sorry, it got so quiet around the issue.

> Question: Is this intended to be in addition to the current vanilla JavaScript version or to replace it? I would personally like to keep a vanilla JavaScript option available.

Updating the typescript code as well as the javascript code can be quiet tedious and error-prone.
I would prefer the typescript code as a single source of truth.
The generated code should be very similar to the current javascript code.

**Comment by Dimanoid** [comment]
Any progress on this?

**Comment by tim-hellhake** [comment]
Actually I'm working on it right now 😄

**Comment by 0x2206** [comment]
Please do not feel pushed, but I am interested in progress on this as well?

**Comment by tim-hellhake** [comment]
Sorry I've been busy maintaining the addons :sweat_smile: .
I'll look at it today.

**Comment by 0x2206** [comment]
Cool, thanks :-) If you need any help just shoot.

**Comment by tim-hellhake** [comment]
> If you need any help just shoot

I'm done with the migration.
I also mentioned you in the PR.
